<table border ="1">
    <?php foreach ($its as $it){
               // var_dump($it);
               echo '<tr>';
                    echo '<th>'. $it->job_title.'</th>';
               echo '</tr>';
            }            
      ?>
    </table>

<?php 
      var_dump($users);
      foreach ($users as $user) {
          foreach ($user as $u){
          var_dump($u);
          }
      }
       
 ?>
    


