<table>
    <tr>
        <th>job title</th>
        <th>job company</th>
        <th>job category</th>
        <th>job deadline</th>
        <th>job description</th>
   </tr>
<?php
foreach ($jobs as $job) {
    echo '<tr>';
	echo'<td>'. $job->getJobTitle().'</td>'; 
        echo'<td>'.($job->getJcat()->getJcatId()).'</td>';
	echo'<td>'.($job->getJcat()->getCom()->getComName()).'</td>'; 
	echo'<td>'.($job->getJcat()->getCat()->getCatName()).'</td>';
        echo'<td>'. $job->getJobDeadline().'</td>'; 
        echo'<td>'. $job->getJobDescription().'</td>'; 
        echo '<td><a href="' . $this->url('home/action', array('action' => 'edit', 'id' =>$job->getJobId())) . '" class="icon-pencil-2"></a></td>';
        echo '<td><input class="url" type="hidden" value="'.$this->url('home',array('action'=>'delete','id'=>$job->getJcat()->getJcatId())).' " />  <a href="delete/'.$job->getJcat()->getJcatId().'" class="icon-remove deleteIcon"> </a> </td>';
        
   echo '</tr>';
    }
?>
</table>
<script type="text/javascript">
	jQuery(document).ready(function (){
		jQuery('.deleteIcon').click(function (){
			var url = jQuery(this).parent().find('.url').val();
			jQuery('#linkDelete').attr('href', url);
			jQuery('#deleteConfirmation').modal('');
		});
	});
</script>